name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Build and Deploy
        run: |
          # Access the secret and pass it to the React app
          echo "REACT_APP_API_TOKEN=${{ secrets.REACT_APP_API_TOKEN }}" >> .env.local

          # Your build and deploy commands here
          npm run build
          # Add any other necessary commands
        env:
          REACT_APP_API_TOKEN: ${{ secrets.REACT_APP_API_TOKEN }}
